### ISSUE TITLE
请教关于项目结构的问题

### ISSUE THREAD

**Issue by mylitteboat** [renjiahua945/Lumos#3]
您好，请问这个项目结构为什么要拆分的这么细啊，部署的话是不是需要多台服务器才行啊，都部署到一台服务器上，这么多项目设置多大内存合适啊

**Comment by renjiahua945** [comment]
> 您好，请问这个项目结构为什么要拆分的这么细啊，部署的话是不是需要多台服务器才行啊，都部署到一台服务器上，这么多项目设置多大内存合适啊

您问出这个问题说明你对maven项目还不太熟悉，部署的话直接把blog-web模块打包了部署就行。和普通项目一样的。

**Comment by mylitteboat** [comment]
> > 您好，请问这个项目结构为什么要拆分的这么细啊，部署的话是不是需要多台服务器才行啊，都部署到一台服务器上，这么多项目设置多大内存合适啊
> 
> 您问出这个问题说明你对maven项目还不太熟悉，部署的话直接把blog-web模块打包了部署就行。和普通项目一样的。

奥奥，明白点了。麻烦再问下，这样拆分的好处是什么呢

**Comment by renjiahua945** [comment]
> > > 您好，请问这个项目结构为什么要拆分的这么细啊，部署的话是不是需要多台服务器才行啊，都部署到一台服务器上，这么多项目设置多大内存合适啊
> > 
> > 
> > 您问出这个问题说明你对maven项目还不太熟悉，部署的话直接把blog-web模块打包了部署就行。和普通项目一样的。
> 
> 奥奥，明白点了。麻烦再问下，这样拆分的好处是什么呢

百度搜maven多模块的好处，如何觉得项目不错，麻烦点个star

**Comment by mylitteboat** [comment]
> > > > 您好，请问这个项目结构为什么要拆分的这么细啊，部署的话是不是需要多台服务器才行啊，都部署到一台服务器上，这么多项目设置多大内存合适啊
> > > 
> > > 
> > > 您问出这个问题说明你对maven项目还不太熟悉，部署的话直接把blog-web模块打包了部署就行。和普通项目一样的。
> > 
> > 
> > 奥奥，明白点了。麻烦再问下，这样拆分的好处是什么呢
> 
> 百度搜maven多模块的好处，如何觉得项目不错，麻烦点个star

好的，谢谢，已star

**Comment by renjiahua945** [comment]
> > > > > 您好，请问这个项目结构为什么要拆分的这么细啊，部署的话是不是需要多台服务器才行啊，都部署到一台服务器上，这么多项目设置多大内存合适啊
> > > > 
> > > > 
> > > > 您问出这个问题说明你对maven项目还不太熟悉，部署的话直接把blog-web模块打包了部署就行。和普通项目一样的。
> > > 
> > > 
> > > 奥奥，明白点了。麻烦再问下，这样拆分的好处是什么呢
> > 
> > 
> > 百度搜maven多模块的好处，如何觉得项目不错，麻烦点个star
> 
> 好的，谢谢，已star
可以通过readme的链接加群
